# fly.toml app configuration file generated for volante-frontend on 2024-10-22T20:12:38-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'volante-frontend'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']


[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
